"""Standalone feature gallery for dygraphs Python.

Run with::

    python -m examples.gallery_pkg
    # or
    uv run python -m examples.gallery_pkg

Opens the gallery in your default browser. No Dash or Shiny required.
"""

from __future__ import annotations

import tempfile
import webbrowser
from pathlib import Path

from . import api, basics, overlays, plotters, plugins
from ._common import render_section

# Order matters — sections render top-to-bottom in the page
_CHAPTERS = [basics, overlays, plotters, plugins, api]


def build_page() -> str:
    sections_html = ""
    n_sections = 0
    n_charts = 0
    for chapter in _CHAPTERS:
        for section_func in chapter.ALL_SECTIONS:
            title, charts = section_func()
            sections_html += render_section(title, charts)
            n_sections += 1
            n_charts += len(charts)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>dygraphs Python — Feature Gallery</title>
<style>
  * {{ box-sizing: border-box; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    max-width: 1200px;
    margin: 0 auto;
    padding: 32px 24px;
    background: #fafafa;
    color: #222;
  }}
  h1 {{
    text-align: center;
    margin-bottom: 8px;
  }}
  .subtitle {{
    text-align: center;
    color: #666;
    margin-bottom: 40px;
  }}
  .section {{
    margin-bottom: 48px;
  }}
  .section h2 {{
    border-bottom: 2px solid #ddd;
    padding-bottom: 8px;
    color: #333;
  }}
  .card {{
    background: #fff;
    border-radius: 8px;
    padding: 16px 20px;
    margin-bottom: 20px;
    box-shadow: 0 1px 4px rgba(0,0,0,0.08);
  }}
  .card h3 {{
    margin: 0 0 8px 0;
    font-size: 14px;
    color: #888;
    font-weight: 500;
  }}
  .toc {{
    background: #fff;
    border-radius: 8px;
    padding: 16px 24px;
    margin-bottom: 32px;
    box-shadow: 0 1px 4px rgba(0,0,0,0.08);
  }}
  .toc ul {{
    columns: 2;
    list-style: none;
    padding: 0;
    margin: 8px 0 0 0;
  }}
  .toc li {{
    padding: 2px 0;
  }}
  .toc a {{
    color: #2980b9;
    text-decoration: none;
  }}
  .toc a:hover {{
    text-decoration: underline;
  }}
</style>
</head>
<body>
<h1>dygraphs Python &mdash; Feature Gallery</h1>
<p class="subtitle">
  Every feature demonstrated in standalone HTML. {n_sections} sections,
  {n_charts} charts.
</p>
{sections_html}
<p style="text-align:center;color:#999;margin-top:48px;">
  Generated by <code>examples/gallery.py</code>
</p>
</body>
</html>"""


def main() -> None:
    page = build_page()
    out = Path(tempfile.mktemp(suffix=".html", prefix="dygraphs_gallery_"))
    out.write_text(page)
    print(f"Gallery written to {out}")
    webbrowser.open(f"file://{out}")
